@extends('layouts.admin')

@section('title', 'Reports Management')

@push('styles')
<style>
  /* Status pills — generated by PHP helper; must stay CSS classes */
  .admin-status-pill {
    display: inline-flex; align-items: center; gap: 4px;
    padding: 3px 10px; border-radius: 9999px;
    font-size: 0.75rem; font-weight: 700; white-space: nowrap;
    cursor: pointer; transition: transform 0.1s ease;
    border: 1px solid transparent;
  }
  .admin-status-pill:hover { transform: scale(1.05); }
  .status-pending     { background: #fef3c7; color: #92400e; border-color: #fde68a; }
  .status-in_progress { background: #dbeafe; color: #1e40af; border-color: #bfdbfe; }
  .status-resolved    { background: #d1fae5; color: #065f46; border-color: #a7f3d0; }
  .status-rejected    { background: #fee2e2; color: #991b1b; border-color: #fecaca; }
  .dark .status-pending     { background: rgba(245,158,11,.15); color: #fcd34d; border-color: rgba(245,158,11,.3); }
  .dark .status-in_progress { background: rgba(59,130,246,.15);  color: #93c5fd; border-color: rgba(59,130,246,.3); }
  .dark .status-resolved    { background: rgba(16,185,129,.15);  color: #6ee7b7; border-color: rgba(16,185,129,.3); }
  .dark .status-rejected    { background: rgba(239,68,68,.15);   color: #fca5a5; border-color: rgba(239,68,68,.3); }

  /* Priority badges — generated by PHP helper */
  .priority-badge { display: inline-flex; align-items: center; gap: 4px; padding: 3px 10px; border-radius: 9999px; font-size: 0.75rem; font-weight: 700; border: 1px solid transparent; }
  .priority-high   { background: rgba(239,68,68,.1);   color: #dc2626; border-color: rgba(239,68,68,.3); }
  .priority-medium { background: rgba(245,158,11,.1);  color: #d97706; border-color: rgba(245,158,11,.3); }
  .priority-low    { background: rgba(16,185,129,.1);  color: #059669; border-color: rgba(16,185,129,.3); }

  /* Bulk bar — JS toggles .show */
  .bulk-actions        { display: none; }
  .bulk-actions.show   { display: flex; }

  /* View toggle — JS toggles .active */
  .view-toggle-btn         { transition: all 0.15s; }
  .view-toggle-btn.active  { background: #059669; color: #fff; border-radius: 0.5rem; }

  /* Animations — JS IntersectionObserver controls playState */
  @keyframes slideInUp   { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: translateY(0); } }
  @keyframes fadeInScale { from { opacity: 0; transform: scale(.97); }       to { opacity: 1; transform: scale(1); }    }
  .slide-in  { animation: slideInUp   0.3s ease both; }
  .fade-scale{ animation: fadeInScale 0.3s ease both; }

  /* Loading spinner — JS creates these inline */
  @keyframes spin { to { transform: rotate(360deg); } }
  .loading-spinner { border: 3px solid #e2e8f0; border-top-color: #059669; border-radius: 50%; animation: spin 0.8s linear infinite; }
</style>
@endpush

@section('content')
@php
  $hasCounts         = isset($statusCounts) && $statusCounts instanceof \Illuminate\Support\Collection;
  $totalReports      = $hasCounts ? $statusCounts->sum()                    : ($reports->total() ?? $reports->count() ?? 0);
  $pendingReports    = $hasCounts ? ($statusCounts['pending'] ?? 0)         : collect($reports)->where('status','pending')->count();
  $inProgressReports = $hasCounts ? ($statusCounts['in_progress'] ?? 0)    : collect($reports)->where('status','in_progress')->count();
  $resolvedReports   = $hasCounts ? ($statusCounts['resolved'] ?? 0)       : collect($reports)->where('status','resolved')->count();

  $adminPill = function($status, $reportId = null) {
    $s     = $status ?? 'pending';
    $label = \Illuminate\Support\Str::headline($s);
    $click = $reportId ? 'onclick="AdminReports.quickStatusChange(this, '.$reportId.', \''.$s.'\')"' : '';
    return '<span class="admin-status-pill status-'.e($s).'" '.$click.'>● '.$label.'</span>';
  };
  $priorityBadge = function($priority) {
    $p = $priority ?? 'medium';
    $icons = ['high' => '🔴', 'medium' => '🟡', 'low' => '🟢'];
    return '<span class="priority-badge priority-'.$p.'">'.($icons[$p] ?? '⚪').' '.ucfirst($p).'</span>';
  };
@endphp

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

  {{-- ── Header ──────────────────────────────────────────────── --}}
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
    <div>
      <h1 class="text-2xl font-bold text-slate-900 dark:text-white">Reports Management</h1>
      <p class="text-sm text-slate-500 dark:text-slate-400 mt-0.5">Monitor, review, and manage all incoming city reports.</p>
    </div>
    <div class="flex items-center gap-2">
      {{-- View toggle --}}
      <div class="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 rounded-lg p-1 border border-slate-200 dark:border-slate-700">
        <button type="button" class="view-toggle-btn active px-3 py-1.5 text-sm font-medium text-slate-600 dark:text-slate-400" data-view="cards">
          <span class="flex items-center gap-1.5">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/></svg>
            Cards
          </span>
        </button>
        <button type="button" class="view-toggle-btn px-3 py-1.5 text-sm font-medium text-slate-600 dark:text-slate-400" data-view="table">
          <span class="flex items-center gap-1.5">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 10h18M3 14h18M10 3v18M3 6a3 3 0 013-3h12a3 3 0 013 3v12a3 3 0 01-3 3H6a3 3 0 01-3-3V6z"/></svg>
            Table
          </span>
        </button>
      </div>

      {{-- Export --}}
      <button type="button" id="exportBtn"
              class="inline-flex items-center gap-1.5 px-3.5 py-2 text-sm font-medium rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
        Export
      </button>
    </div>
  </div>

  {{-- ── Stat Cards ──────────────────────────────────────────── --}}
  <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
    <div class="fade-scale bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 relative overflow-hidden">
      <div class="absolute top-0 left-0 right-0 h-0.5 bg-slate-400"></div>
      <div class="text-2xl font-bold text-slate-900 dark:text-white">{{ number_format($totalReports) }}</div>
      <div class="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">Total Reports</div>
      <svg class="absolute top-4 right-4 w-8 h-8 text-slate-200 dark:text-slate-700" fill="currentColor" viewBox="0 0 24 24"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/></svg>
    </div>
    <div class="fade-scale bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 relative overflow-hidden" style="animation-delay:.05s">
      <div class="absolute top-0 left-0 right-0 h-0.5 bg-amber-400"></div>
      <div class="text-2xl font-bold text-amber-600">{{ number_format($pendingReports) }}</div>
      <div class="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">Pending Review</div>
      <svg class="absolute top-4 right-4 w-8 h-8 text-amber-100 dark:text-amber-900/30" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z"/></svg>
    </div>
    <div class="fade-scale bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 relative overflow-hidden" style="animation-delay:.1s">
      <div class="absolute top-0 left-0 right-0 h-0.5 bg-indigo-400"></div>
      <div class="text-2xl font-bold text-indigo-600">{{ number_format($inProgressReports) }}</div>
      <div class="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">In Progress</div>
      <svg class="absolute top-4 right-4 w-8 h-8 text-indigo-100 dark:text-indigo-900/30" fill="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
    </div>
    <div class="fade-scale bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 relative overflow-hidden" style="animation-delay:.15s">
      <div class="absolute top-0 left-0 right-0 h-0.5 bg-emerald-400"></div>
      <div class="text-2xl font-bold text-emerald-600">{{ number_format($resolvedReports) }}</div>
      <div class="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">Resolved</div>
      <svg class="absolute top-4 right-4 w-8 h-8 text-emerald-100 dark:text-emerald-900/30" fill="currentColor" viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>
    </div>
  </div>

  {{-- ── Quick Actions ─────────────────────────────────────── --}}
  <div class="slide-in bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 mb-6">
    <h3 class="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Quick Actions</h3>
    <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
      @foreach([
        ['label'=>'Pending',      'icon'=>'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',         'fn'=>"AdminReports.filterByStatus('pending')"],
        ['label'=>'In Progress',  'icon'=>'M13 10V3L4 14h7v7l9-11h-7z',                           'fn'=>"AdminReports.filterByStatus('in_progress')"],
        ['label'=>'High Priority','icon'=>'M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z','fn'=>'AdminReports.filterByPriority()'],
        ['label'=>"Today's",      'icon'=>'M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z','fn'=>"AdminReports.filterByDate('today')"],
        ['label'=>'Bulk Select',  'icon'=>'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2','fn'=>'','id'=>'bulkToggleBtn'],
        ['label'=>'Export CSV',   'icon'=>'M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z','fn'=>'AdminReports.generateReport()'],
      ] as $qa)
        <button type="button"
                @if(!empty($qa['id'])) id="{{ $qa['id'] }}" @endif
                @if($qa['fn']) onclick="{{ $qa['fn'] }}" @endif
                class="flex flex-col items-center gap-1.5 p-3 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-700/50 text-slate-600 dark:text-slate-400 hover:bg-emerald-50 hover:text-emerald-700 hover:border-emerald-200 dark:hover:bg-emerald-900/20 dark:hover:text-emerald-400 transition-colors text-center">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="{{ $qa['icon'] }}"/></svg>
          <span class="text-xs font-medium leading-tight">{{ $qa['label'] }}</span>
        </button>
      @endforeach
    </div>
  </div>

  {{-- ── Flash ─────────────────────────────────────────────── --}}
  @if(session('success'))
    <div class="mb-6 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 dark:bg-emerald-900/20 dark:border-emerald-800 px-5 py-3.5 text-sm text-emerald-800 dark:text-emerald-300 shadow-sm">
      <svg class="w-5 h-5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/></svg>
      {{ session('success') }}
    </div>
  @endif

  {{-- ── Bulk Actions Bar ─────────────────────────────────── --}}
  <div class="bulk-actions items-center gap-4 flex-wrap mb-6 bg-white dark:bg-slate-800 border border-emerald-200 dark:border-emerald-800 rounded-xl px-5 py-3.5 shadow-sm"
       id="bulkActions">
    <div class="flex items-center gap-3 flex-1 min-w-0">
      <div class="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-900/40">
        <svg class="w-5 h-5 text-emerald-600 dark:text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/></svg>
      </div>
      <div>
        <span class="font-semibold text-slate-800 dark:text-slate-200"><span id="selectedCount">0</span> selected</span>
        <p class="text-xs text-slate-500 dark:text-slate-400">Choose an action</p>
      </div>
    </div>
    <div class="flex flex-wrap items-center gap-2">
      <div class="flex gap-1 bg-slate-100 dark:bg-slate-700 rounded-lg p-1">
        @foreach(['pending'=>'Pending','in_progress'=>'In Progress','resolved'=>'Resolved'] as $sv => $sl)
          <button type="button" onclick="AdminReports.bulkAction('change_status', '{{ $sv }}')"
                  class="px-3 py-1.5 text-xs font-semibold rounded-md text-slate-600 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-600 hover:shadow-sm transition-all">
            {{ $sl }}
          </button>
        @endforeach
      </div>
      <button type="button" onclick="AdminReports.bulkExport()"
              class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3"/></svg>
        Export
      </button>
      <button type="button" onclick="AdminReports.bulkAction('delete')"
              class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-600 dark:text-red-400 hover:bg-red-100 transition-colors">
        <svg class="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24"><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg>
        Delete
      </button>
      <button type="button" onclick="AdminReports.clearBulkSelection()"
              class="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold rounded-lg border border-slate-200 dark:border-slate-700 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
        Clear
      </button>
    </div>
  </div>

  {{-- ── Filters ───────────────────────────────────────────── --}}
  <div class="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-5 mb-6">
    <form method="GET" action="{{ route('admin.reports.index') }}" id="adminFiltersForm">
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-3">
        {{-- Search --}}
        <div class="sm:col-span-2 xl:col-span-2 relative">
          <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35M17 11A6 6 0 115 11a6 6 0 0112 0z"/></svg>
          <input type="search" name="q" value="{{ request('q','') }}" placeholder="Search title, user, ID…"
                 class="w-full pl-9 pr-4 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
        </div>

        {{-- City --}}
        <select name="city" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="">All cities</option>
          @foreach(($cities ?? []) as $c)
            <option value="{{ $c }}" @selected(request('city')===$c)>{{ $c }}</option>
          @endforeach
        </select>

        {{-- Category --}}
        <select name="category" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="">All categories</option>
          @foreach(($categories ?? []) as $cat)
            <option value="{{ $cat }}" @selected(request('category')===$cat)>{{ ucfirst($cat) }}</option>
          @endforeach
        </select>

        {{-- Status --}}
        <select name="status" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="">All statuses</option>
          @foreach(['pending','in_progress','resolved','rejected'] as $s)
            <option value="{{ $s }}" @selected(request('status')===$s)>{{ \Illuminate\Support\Str::headline($s) }}</option>
          @endforeach
        </select>
      </div>

      {{-- Second row --}}
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-3 mt-3">
        <div class="sm:col-span-2 flex flex-wrap items-center gap-2">
          <label class="text-xs font-medium text-slate-500 dark:text-slate-400 w-full">Date range</label>
          <input type="date" name="from" value="{{ request('from') }}"
                 class="flex-1 min-w-0 px-3 py-2 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500">
          <span class="text-xs text-slate-400">to</span>
          <input type="date" name="to" value="{{ request('to') }}"
                 class="flex-1 min-w-0 px-3 py-2 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500">
        </div>

        <select name="priority" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="">All priorities</option>
          <option value="high"   @selected(request('priority')==='high')>High Priority</option>
          <option value="medium" @selected(request('priority')==='medium')>Medium Priority</option>
          <option value="low"    @selected(request('priority')==='low')>Low Priority</option>
        </select>

        <select name="assigned_to" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="">All assignments</option>
          <option value="me"         @selected(request('assigned_to')==='me')>Assigned to me</option>
          <option value="unassigned" @selected(request('assigned_to')==='unassigned')>Unassigned</option>
          <option value="others"     @selected(request('assigned_to')==='others')>Assigned to others</option>
        </select>

        @php $sort = request('sort','newest'); @endphp
        <select id="sort" name="sort" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          <option value="newest"   @selected($sort==='newest')>Newest first</option>
          <option value="oldest"   @selected($sort==='oldest')>Oldest first</option>
          <option value="priority" @selected($sort==='priority')>Priority (High→Low)</option>
          <option value="status"   @selected($sort==='status')>Status (A→Z)</option>
          <option value="city"     @selected($sort==='city')>City (A→Z)</option>
          <option value="updated"  @selected($sort==='updated')>Recently updated</option>
        </select>

        <select id="per_page" name="per_page" class="px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition">
          @foreach([12,18,24,30,48] as $pp)
            <option value="{{ $pp }}" @selected((int)request('per_page',18)===$pp)>Show {{ $pp }}</option>
          @endforeach
        </select>
      </div>

      <div class="flex flex-wrap items-center justify-between gap-3 mt-4 pt-4 border-t border-slate-100 dark:border-slate-700">
        <div class="flex flex-wrap gap-2">
          <button type="submit"
                  class="inline-flex items-center gap-1.5 px-4 py-2 text-sm font-semibold rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35M17 11A6 6 0 115 11a6 6 0 0112 0z"/></svg>
            Apply Filters
          </button>
          <a href="{{ route('admin.reports.index') }}"
             class="inline-flex items-center gap-1.5 px-4 py-2 text-sm font-semibold rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
            Clear All
          </a>
        </div>
        <div class="flex flex-wrap gap-2">
          <button type="button" id="saveFiltersBtn"
                  class="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-slate-200 dark:border-slate-700 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"/></svg>
            Save Filter
          </button>
          <button type="button" id="copyLinkBtn"
                  class="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-slate-200 dark:border-slate-700 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"/></svg>
            Copy Link
          </button>
          <button type="button" id="refreshBtn"
                  class="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg border border-slate-200 dark:border-slate-700 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            Refresh
          </button>
        </div>
      </div>

      {{-- Active filter chips --}}
      @if(request()->hasAny(['q','city','category','status','priority','assigned_to','from','to']))
        <div class="mt-3 pt-3 border-t border-slate-100 dark:border-slate-700 flex flex-wrap items-center gap-2">
          <span class="text-xs font-semibold text-slate-500 dark:text-slate-400">Active:</span>
          @foreach(['q'=>'Search','city'=>'City','category'=>'Category','status'=>'Status','priority'=>'Priority'] as $k=>$l)
            @if(request($k))
              <span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-full bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
                {{ $l }}: {{ \Illuminate\Support\Str::headline(request($k)) }}
              </span>
            @endif
          @endforeach
          @if(request('from') || request('to'))
            <span class="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-full bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
              Date: {{ request('from','Start') }} → {{ request('to','End') }}
            </span>
          @endif
        </div>
      @endif
    </form>
  </div>

  {{-- ── Cards View ────────────────────────────────────────── --}}
  <div id="cardsView" class="view-content">
    @if($reports->isEmpty())
      <div class="bg-white dark:bg-slate-800 rounded-xl border border-dashed border-slate-300 dark:border-slate-600 p-16 text-center">
        <div class="w-14 h-14 rounded-2xl bg-slate-100 dark:bg-slate-700 flex items-center justify-center mx-auto mb-4">
          <svg class="w-7 h-7 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
        </div>
        <h3 class="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1">No reports found</h3>
        <p class="text-xs text-slate-400 mb-5">Try adjusting your filters or search criteria.</p>
        <a href="{{ route('admin.reports.index') }}"
           class="inline-flex items-center gap-1.5 px-4 py-2 text-sm font-semibold rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">
          Reset Filters
        </a>
      </div>
    @else
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        @foreach($reports as $report)
          @php
            $daysSince = optional($report->created_at)->diffInDays(now()) ?? 0;
            $priority  = $daysSince > 7 ? 'high' : ($daysSince > 3 ? 'medium' : 'low');
            if ($report->status === 'pending' && $daysSince > 3) $priority = 'high';
            $commentsCount     = method_exists($report,'comments')     ? $report->comments()->count()     : ($report->comments_count ?? 0);
            $endorsementsCount = method_exists($report,'endorsements') ? $report->endorsements()->count() : ($report->likes_count ?? 0);
          @endphp

          <article class="admin-report-card slide-in bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm hover:shadow-md hover:border-slate-300 dark:hover:border-slate-600 transition-all overflow-hidden relative"
                   style="animation-delay: {{ $loop->index * 0.04 }}s"
                   data-report-id="{{ $report->id }}">

            {{-- Bulk checkbox --}}
            <div class="absolute top-3 left-3 z-10">
              <input type="checkbox" class="bulk-checkbox w-4 h-4 accent-emerald-600 rounded"
                     value="{{ $report->id }}" onchange="AdminReports.updateBulkSelection()" style="display:none">
            </div>

            {{-- Photo or map preview --}}
            @if($report->photo)
              <div class="relative">
                <img src="{{ Storage::url($report->photo) }}" alt="{{ $report->title }}"
                     class="w-full h-40 object-cover">
                <div class="absolute top-3 right-3">{!! $priorityBadge($priority) !!}</div>
              </div>
            @elseif($report->static_map_url)
              <div class="relative">
                <img src="{{ $report->static_map_url }}" alt="Map preview" class="w-full h-40 object-cover">
                <div class="absolute top-3 right-3">{!! $priorityBadge($priority) !!}</div>
              </div>
            @endif

            <div class="p-5">
              {{-- Header --}}
              <div class="admin-report-head flex items-start justify-between gap-3 mb-3">
                <h3 class="text-sm font-bold text-slate-800 dark:text-slate-100 leading-snug line-clamp-2 flex-1">{{ $report->title }}</h3>
                @if(!$report->photo && !$report->static_map_url)
                  <div class="flex-shrink-0">{!! $priorityBadge($priority) !!}</div>
                @endif
              </div>

              <div class="mb-3">{!! $adminPill($report->status, $report->id) !!}</div>

              {{-- Meta --}}
              <dl class="space-y-1.5 text-xs text-slate-500 dark:text-slate-400 mb-4">
                <dd class="flex items-center gap-1.5">
                  <svg class="w-3.5 h-3.5 flex-shrink-0 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                  <span class="font-medium text-slate-700 dark:text-slate-300">{{ $report->user->name ?? 'Anonymous' }}</span>
                  <span class="text-slate-400">·</span>
                  <span>#{{ $report->id }}</span>
                </dd>
                @if($report->city_corporation || $report->location)
                  <dd class="flex items-center gap-1.5">
                    <svg class="w-3.5 h-3.5 flex-shrink-0 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a2 2 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0zM15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
                    {{ $report->city_corporation ?? $report->location }}
                  </dd>
                @endif
                @if($report->category)
                  <dd class="flex items-center gap-1.5">
                    <svg class="w-3.5 h-3.5 flex-shrink-0 text-violet-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
                    {{ ucfirst($report->category) }}
                  </dd>
                @endif
                <dd class="flex items-center gap-1.5">
                  <svg class="w-3.5 h-3.5 flex-shrink-0 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                  {{ optional($report->created_at)->format('M d, Y') }}
                  @if($daysSince > 0)
                    <span class="px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-100 dark:bg-slate-700 text-slate-500">{{ $daysSince }}d ago</span>
                  @endif
                </dd>
              </dl>

              {{-- Engagement --}}
              <div class="flex items-center gap-3 text-xs text-slate-400 mb-4">
                <span class="flex items-center gap-1">
                  <svg class="w-3 h-3" fill="currentColor" viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h4l4 4 4-4h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/></svg>
                  {{ $commentsCount }}
                </span>
                <span class="flex items-center gap-1">
                  <svg class="w-3 h-3" fill="currentColor" viewBox="0 0 24 24"><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>
                  {{ $endorsementsCount }}
                </span>
              </div>

              {{-- Actions --}}
              <div class="flex items-center gap-2 pt-3 border-t border-slate-100 dark:border-slate-700">
                <a href="{{ route('admin.reports.show', $report) }}"
                   class="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs font-semibold rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                  Review
                </a>

                <div class="flex gap-1" id="action-buttons-{{ $report->id }}">
                  @if($report->status === 'pending')
                    <button type="button" onclick="AdminReports.quickAction(event, {{ $report->id }}, 'approve')" title="Approve"
                            class="p-2 rounded-lg border border-emerald-200 dark:border-emerald-800 text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-900/20 transition-colors">
                      <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                    </button>
                    <button type="button" onclick="AdminReports.quickAction(event, {{ $report->id }}, 'reject')" title="Reject"
                            class="p-2 rounded-lg border border-red-200 dark:border-red-800 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors">
                      <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                  @endif
                  <button type="button" onclick="AdminReports.assignToMe(event, {{ $report->id }})" title="Assign to me"
                          class="p-2 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                  </button>
                </div>
              </div>
            </div>
          </article>
        @endforeach
      </div>
    @endif
  </div>

  {{-- ── Table View ────────────────────────────────────────── --}}
  <div id="tableView" class="view-content hidden">
    <div class="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
      <div class="overflow-x-auto">
        <table class="w-full border-collapse text-sm">
          <thead>
            <tr class="bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700">
              <th class="w-10 px-4 py-3">
                <input type="checkbox" id="selectAll" class="bulk-checkbox w-4 h-4 accent-emerald-600 rounded"
                       onchange="AdminReports.toggleSelectAll()">
              </th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Report</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">User</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Location</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Status</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Priority</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Created</th>
              <th class="px-4 py-3 text-left font-semibold text-slate-600 dark:text-slate-400">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-slate-100 dark:divide-slate-700">
            @forelse($reports as $report)
              @php
                $daysSince = optional($report->created_at)->diffInDays(now()) ?? 0;
                $priority  = $daysSince > 7 ? 'high' : ($daysSince > 3 ? 'medium' : 'low');
                if ($report->status === 'pending' && $daysSince > 3) $priority = 'high';
              @endphp
              <tr class="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors" data-report-id="{{ $report->id }}">
                <td class="px-4 py-3">
                  <input type="checkbox" class="bulk-checkbox w-4 h-4 accent-emerald-600 rounded"
                         value="{{ $report->id }}" onchange="AdminReports.updateBulkSelection()">
                </td>
                <td class="px-4 py-3 max-w-xs">
                  <a href="{{ route('admin.reports.show', $report) }}"
                     class="font-medium text-slate-800 dark:text-slate-200 hover:text-emerald-600 dark:hover:text-emerald-400 line-clamp-1 block transition-colors">{{ $report->title }}</a>
                  <div class="text-xs text-slate-400 mt-0.5">#{{ $report->id }} · {{ $report->category ?? 'General' }}</div>
                </td>
                <td class="px-4 py-3">
                  <div class="font-medium text-slate-700 dark:text-slate-300">{{ $report->user->name ?? 'Anonymous' }}</div>
                  <div class="text-xs text-slate-400">{{ $report->user->email ?? '—' }}</div>
                </td>
                <td class="px-4 py-3 max-w-xs">
                  <div class="font-medium text-slate-700 dark:text-slate-300">{{ $report->city_corporation ?? '—' }}</div>
                  <div class="text-xs text-slate-400 truncate">{{ $report->short_address ?? $report->location ?? '—' }}</div>
                </td>
                <td class="px-4 py-3">{!! $adminPill($report->status, $report->id) !!}</td>
                <td class="px-4 py-3">{!! $priorityBadge($priority) !!}</td>
                <td class="px-4 py-3 whitespace-nowrap text-xs text-slate-500 dark:text-slate-400">
                  <div>{{ optional($report->created_at)->format('M d, Y') }}</div>
                  <div>{{ optional($report->created_at)->format('h:i A') }}</div>
                </td>
                <td class="px-4 py-3">
                  <div class="flex gap-1" id="table-action-buttons-{{ $report->id }}">
                    <a href="{{ route('admin.reports.show', $report) }}"
                       class="p-1.5 rounded-md bg-emerald-600 text-white hover:bg-emerald-700 transition-colors" title="Review">
                      <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                    </a>
                    @if($report->status === 'pending')
                      <button type="button" onclick="AdminReports.quickAction(event, {{ $report->id }}, 'approve')"
                              class="p-1.5 rounded-md border border-emerald-200 text-emerald-600 hover:bg-emerald-50 transition-colors" title="Approve">
                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                      </button>
                      <button type="button" onclick="AdminReports.quickAction(event, {{ $report->id }}, 'reject')"
                              class="p-1.5 rounded-md border border-red-200 text-red-500 hover:bg-red-50 transition-colors" title="Reject">
                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
                      </button>
                    @endif
                  </div>
                </td>
              </tr>
            @empty
              <tr>
                <td colspan="8" class="py-12 text-center text-sm text-slate-400 dark:text-slate-500">No reports match your criteria.</td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>

  {{-- ── Pagination ────────────────────────────────────────── --}}
  @if(method_exists($reports,'links'))
    <div class="mt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
      <div class="text-sm text-slate-500 dark:text-slate-400">
        Showing {{ $reports->firstItem() ?? 0 }}–{{ $reports->lastItem() ?? 0 }} of {{ number_format($reports->total()) }} results
      </div>
      <div>{{ $reports->appends(request()->query())->links() }}</div>
    </div>
  @endif

</div>

{{-- Loading overlay --}}
<div id="loadingOverlay" class="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm hidden items-center justify-center">
  <div class="bg-white dark:bg-slate-800 rounded-xl p-6 shadow-xl flex items-center gap-4">
    <div class="loading-spinner w-8 h-8"></div>
    <div>
      <div class="font-semibold text-slate-800 dark:text-slate-200">Processing…</div>
      <div class="text-sm text-slate-500 dark:text-slate-400">Please wait.</div>
    </div>
  </div>
</div>

@endsection

@push('scripts')
<script>
// Define CSRF token meta tag check
document.addEventListener('DOMContentLoaded', function() {
  // Ensure CSRF token meta tag exists
  if (!document.querySelector('meta[name="csrf-token"]')) {
    const metaTag = document.createElement('meta');
    metaTag.name = 'csrf-token';
    metaTag.content = '{{ csrf_token() }}';
    document.head.appendChild(metaTag);
  }
});

window.ADMIN_ROUTES = {
  status: '{{ route("admin.reports.status", ["report" => "__ID__"]) }}',
  assign: '{{ route("admin.reports.assign", ["report" => "__ID__"]) }}',
  bulk:   '{{ route("admin.reports.bulk") }}',
  approve: '{{ route("admin.reports.approve", ["report" => "__ID__"]) }}',
  reject:  '{{ route("admin.reports.reject", ["report" => "__ID__"]) }}',
};

// Enhanced Admin Reports Management System
window.AdminReports = (function(){
  'use strict';

  const state = {
    selectedReports: new Set(),
    bulkMode: false,
    isLoading: false
  };

  const elements = {
    form: null,
    loadingOverlay: null,
    bulkActions: null,
    selectedCount: null,
    bulkCheckboxes: null,
    selectAllCheckbox: null
  };

  function init() {
    initializeElements();
    bindEvents();
    setupAutoSubmit();
    setupViewToggle();
    setupAnimations();
    setupKeyboardShortcuts();

    console.log('AdminReports initialized successfully');
  }

  function initializeElements() {
    elements.form = document.getElementById('adminFiltersForm');
    elements.loadingOverlay = document.getElementById('loadingOverlay');
    elements.bulkActions = document.getElementById('bulkActions');
    elements.selectedCount = document.getElementById('selectedCount');
    elements.bulkCheckboxes = document.querySelectorAll('.bulk-checkbox:not(#selectAll)');
    elements.selectAllCheckbox = document.getElementById('selectAll');
  }

  function getCsrfToken() {
    const metaTag = document.querySelector('meta[name="csrf-token"]');
    if (!metaTag) {
      console.error('CSRF token meta tag not found');
      return '';
    }
    return metaTag.content;
  }

  function showLoading() {
    if (elements.loadingOverlay) {
      elements.loadingOverlay.style.display = 'flex';
    }
    state.isLoading = true;
  }

  function hideLoading() {
    if (elements.loadingOverlay) {
      elements.loadingOverlay.style.display = 'none';
    }
    state.isLoading = false;
  }

  function toast(message, type = 'success') {
    // Remove existing toasts
    document.querySelectorAll('.toast').forEach(t => t.remove());

    const el = document.createElement('div');
    el.role = 'status';
    el.ariaLive = 'polite';
    el.textContent = message;
    el.className = 'toast fixed left-1/2 transform -translate-x-1/2 bottom-8 z-50 px-6 py-3 rounded-xl font-medium text-white shadow-lg backdrop-blur-sm transition-all duration-300';

    const bgColor = type === 'error' ? 'linear-gradient(135deg,#ef4444,#dc2626)' :
                   type === 'warning' ? 'linear-gradient(135deg,#f59e0b,#d97706)' :
                                        'linear-gradient(135deg,#10b981,#059669)';
    el.style.background = bgColor;

    document.body.appendChild(el);

    setTimeout(() => {
      el.style.opacity = '0';
      el.style.transform = 'translate(-50%,1rem)';
    }, 2500);

    setTimeout(() => el.remove(), 3000);
  }

  function bindEvents() {
    // Export button
    const exportBtn = document.getElementById('exportBtn');
    if (exportBtn) {
      exportBtn.addEventListener('click', handleExport);
    }

    // Save filters button
    const saveFiltersBtn = document.getElementById('saveFiltersBtn');
    if (saveFiltersBtn) {
      saveFiltersBtn.addEventListener('click', handleSaveFilters);
    }

    // Copy link button
    const copyLinkBtn = document.getElementById('copyLinkBtn');
    if (copyLinkBtn) {
      copyLinkBtn.addEventListener('click', handleCopyLink);
    }

    // Refresh button
    const refreshBtn = document.getElementById('refreshBtn');
    if (refreshBtn) {
      refreshBtn.addEventListener('click', () => window.location.reload());
    }

    // Bulk toggle button
    const bulkToggleBtn = document.getElementById('bulkToggleBtn');
    if (bulkToggleBtn) {
      bulkToggleBtn.addEventListener('click', toggleBulkMode);
    }
  }

  function setupAutoSubmit() {
    if (!elements.form) return;

    // Auto-submit for select elements
    const selectElements = ['per_page', 'sort', 'city', 'category', 'status', 'priority', 'assigned_to'];
    selectElements.forEach(name => {
      const select = elements.form.querySelector(`select[name="${name}"]`);
      if (select) {
        select.addEventListener('change', () => {
          showLoading();
          setTimeout(() => elements.form.submit(), 100);
        });
      }
    });

    // Auto-submit for date inputs
    ['from', 'to'].forEach(name => {
      const input = elements.form.querySelector(`input[name="${name}"]`);
      if (input) {
        input.addEventListener('change', () => {
          showLoading();
          setTimeout(() => elements.form.submit(), 100);
        });
      }
    });

    // Debounced search input
    const searchInput = elements.form.querySelector('input[name="q"]');
    if (searchInput) {
      let timeout;
      let lastValue = searchInput.value;

      searchInput.addEventListener('input', (e) => {
        clearTimeout(timeout);
        const value = e.target.value.trim();

        if (value !== lastValue && (value.length >= 2 || value.length === 0)) {
          timeout = setTimeout(() => {
            lastValue = value;
            showLoading();
            elements.form.submit();
          }, 500);
        }
      });
    }
  }

  function setupViewToggle() {
    const viewToggleButtons = document.querySelectorAll('.view-toggle-btn');
    const cardsView = document.getElementById('cardsView');
    const tableView = document.getElementById('tableView');

    viewToggleButtons.forEach(btn => {
      btn.addEventListener('click', () => {
        const view = btn.dataset.view;

        // Update button states
        viewToggleButtons.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        // Toggle views
        if (view === 'cards') {
          cardsView.style.display = 'block';
          tableView.style.display = 'none';
          localStorage.setItem('adminViewPreference', 'cards');
        } else {
          cardsView.style.display = 'none';
          tableView.style.display = 'block';
          localStorage.setItem('adminViewPreference', 'table');
        }
      });
    });

    // Restore saved view preference
    const savedView = localStorage.getItem('adminViewPreference');
    if (savedView) {
      const btn = document.querySelector(`[data-view="${savedView}"]`);
      if (btn) btn.click();
    }
  }

  function setupAnimations() {
    const observer = new IntersectionObserver((entries, obs) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.style.animationPlayState = 'running';
          obs.unobserve(entry.target);
        }
      });
    }, { rootMargin: '0px 0px -5% 0px', threshold: 0.1 });

    document.querySelectorAll('.slide-in, .fade-scale').forEach(el => {
      el.style.animationPlayState = 'paused';
      observer.observe(el);
    });
  }

  function setupKeyboardShortcuts() {
    document.addEventListener('keydown', (e) => {
      // Ctrl+K or Cmd+K to focus search
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        const searchInput = elements.form?.querySelector('input[name="q"]');
        if (searchInput) {
          searchInput.focus();
          searchInput.select();
        }
      }

      // Escape to clear search
      if (e.key === 'Escape') {
        const activeElement = document.activeElement;
        if (activeElement?.name === 'q') {
          activeElement.value = '';
          activeElement.blur();
          if (elements.form) elements.form.submit();
        }
      }
    });
  }

  // Public methods
  function updateBulkSelection() {
    state.selectedReports.clear();
    elements.bulkCheckboxes.forEach(cb => {
      if (cb.checked) {
        state.selectedReports.add(cb.value);
      }
    });

    if (elements.selectedCount) {
      elements.selectedCount.textContent = state.selectedReports.size;
    }

    if (elements.bulkActions) {
      elements.bulkActions.classList.toggle('show', state.selectedReports.size > 0);
    }

    // Update select all checkbox state
    if (elements.selectAllCheckbox) {
      const total = elements.bulkCheckboxes.length;
      const selected = state.selectedReports.size;

      elements.selectAllCheckbox.checked = selected > 0 && selected === total;
      elements.selectAllCheckbox.indeterminate = selected > 0 && selected < total;
    }
  }

  function toggleSelectAll() {
    const checked = elements.selectAllCheckbox?.checked || false;
    elements.bulkCheckboxes.forEach(cb => {
      cb.checked = checked;
    });
    updateBulkSelection();
  }

  function toggleBulkMode() {
    state.bulkMode = !state.bulkMode;
    const bulkToggleBtn = document.getElementById('bulkToggleBtn');

    // Toggle visibility of bulk checkboxes
    document.querySelectorAll('.bulk-checkbox').forEach(cb => {
      cb.style.display = state.bulkMode ? 'block' : 'none';
    });

    // Update button state
    if (bulkToggleBtn) {
      bulkToggleBtn.classList.toggle('active', state.bulkMode);
    }

    // Clear selection if disabling bulk mode
    if (!state.bulkMode) {
      state.selectedReports.clear();
      if (elements.bulkActions) {
        elements.bulkActions.classList.remove('show');
      }
      document.querySelectorAll('.bulk-checkbox').forEach(cb => {
        cb.checked = false;
      });
    }
  }

  async function quickAction(event, reportId, action) {
    const btn = event?.currentTarget;
    const originalContent = btn?.innerHTML;
    const csrfToken = getCsrfToken();

    if (!csrfToken) {
      toast('Security token missing. Please refresh the page.', 'error');
      return;
    }

    try {
      let url, method, body, newStatus;

      if (action === 'approve') {
        url = window.ADMIN_ROUTES.approve.replace('__ID__', reportId);
        method = 'POST';
        body = null;
        newStatus = 'in_progress';
      } else if (action === 'reject') {
        url = window.ADMIN_ROUTES.reject.replace('__ID__', reportId);
        method = 'DELETE';
        body = null;
        newStatus = 'rejected';
      } else {
        url = window.ADMIN_ROUTES.status.replace('__ID__', reportId);
        method = 'PATCH';
        body = new URLSearchParams({ status: action });
        newStatus = action;
      }

      // Show loading state on button
      if (btn?.tagName === 'BUTTON') {
        btn.disabled = true;
        btn.innerHTML = '<div class="loading-spinner" style="width:1rem;height:1rem"></div>';
      }

      const response = await fetch(url, {
        method,
        headers: {
          'X-CSRF-TOKEN': csrfToken,
          'X-Requested-With': 'XMLHttpRequest',
          'Accept': 'application/json',
          ...(body ? { 'Content-Type': 'application/x-www-form-urlencoded' } : {})
        },
        body
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        throw new Error(data.message || `HTTP ${response.status}: Request failed`);
      }

      // Update UI
      updateReportStatus(reportId, newStatus, data.deleted);

      // Show success message
      if (data.deleted) {
        toast('Report rejected and deleted successfully');
      } else {
        toast(`Report ${action}d successfully`);
      }

      // Remove approve/reject buttons after action
      if (action === 'approve' || action === 'reject') {
        removeActionButtons(reportId);
      }

    } catch (error) {
      console.error('Quick action failed:', error);
      toast(error.message || 'Action failed. Please try again.', 'error');
    } finally {
      if (btn?.tagName === 'BUTTON' && btn.parentNode) {
        btn.disabled = false;
        btn.innerHTML = originalContent;
      }
    }
  }

  function updateReportStatus(reportId, newStatus, deleted = false) {
    const reportCard = document.querySelector(`[data-report-id="${reportId}"]`);

    if (deleted) {
      if (reportCard) {
        reportCard.style.transition = 'all 0.3s ease';
        reportCard.style.opacity = '0';
        reportCard.style.transform = 'translateY(-20px)';
        setTimeout(() => reportCard.remove(), 300);
      }
      return;
    }

    // Update status pills
    const statusPills = document.querySelectorAll(`[data-report-id="${reportId}"] .admin-status-pill`);
    statusPills.forEach(pill => {
      pill.className = `admin-status-pill status-${newStatus}`;
      pill.textContent = `● ${newStatus.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}`;
    });
  }

  function removeActionButtons(reportId) {
    // Remove from card view
    const cardButtons = document.querySelector(`#action-buttons-${reportId}`);
    if (cardButtons) {
      cardButtons.querySelectorAll('button[onclick*="approve"], button[onclick*="reject"]').forEach(btn => {
        btn.style.transition = 'all 0.2s ease';
        btn.style.opacity = '0';
        btn.style.transform = 'scale(0.8)';
        setTimeout(() => btn.remove(), 200);
      });
    }

    // Remove from table view
    const tableButtons = document.querySelector(`#table-action-buttons-${reportId}`);
    if (tableButtons) {
      tableButtons.querySelectorAll('button[onclick*="approve"], button[onclick*="reject"]').forEach(btn => {
        btn.style.transition = 'all 0.2s ease';
        btn.style.opacity = '0';
        btn.style.transform = 'scale(0.8)';
        setTimeout(() => btn.remove(), 200);
      });
    }
  }

  async function assignToMe(event, reportId) {
    const btn = event?.currentTarget;
    const originalContent = btn?.innerHTML;

    if (btn) btn.disabled = true;

    try {
      const url = window.ADMIN_ROUTES.assign.replace('__ID__', reportId);
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'X-CSRF-TOKEN': getCsrfToken(),
          'X-Requested-With': 'XMLHttpRequest',
          'Accept': 'application/json'
        }
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: Assignment failed`);
      }

      toast('Report assigned to you successfully');
    } catch (error) {
      console.error('Assignment failed:', error);
      toast('Assignment failed. Please try again.', 'error');
    } finally {
      if (btn) {
        btn.disabled = false;
        btn.innerHTML = originalContent;
      }
    }
  }

  async function bulkAction(action, status = null) {
    if (state.selectedReports.size === 0) {
      toast('Please select reports first', 'warning');
      return;
    }

    const actionLabel = action === 'change_status' ? `change status to ${status}` : action;
    const confirmMessage = `Are you sure you want to ${actionLabel} for ${state.selectedReports.size} report(s)?`;
    if (!confirm(confirmMessage)) return;

    showLoading();

    try {
      const response = await fetch(window.ADMIN_ROUTES.bulk, {
        method: 'POST',
        headers: {
          'X-CSRF-TOKEN': getCsrfToken(),
          'X-Requested-With': 'XMLHttpRequest',
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          report_ids: Array.from(state.selectedReports),
          action,
          status
        })
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        throw new Error(data.message || `HTTP ${response.status}: Bulk action failed`);
      }

      toast(data.message || `Bulk ${action} completed successfully`);
      setTimeout(() => window.location.reload(), 1000);

    } catch (error) {
      console.error('Bulk action failed:', error);
      toast(error.message || 'Bulk action failed. Please try again.', 'error');
    } finally {
      hideLoading();
    }
  }

  function clearBulkSelection() {
    state.selectedReports.clear();
    elements.bulkCheckboxes.forEach(cb => { cb.checked = false; });
    if (elements.selectAllCheckbox) elements.selectAllCheckbox.checked = false;
    if (elements.bulkActions) elements.bulkActions.classList.remove('show');
    if (elements.selectedCount) elements.selectedCount.textContent = '0';
  }

  function bulkExport() {
    if (state.selectedReports.size === 0) {
      toast('Please select reports first', 'warning');
      return;
    }

    // Create a CSV export
    const reportIds = Array.from(state.selectedReports);
    const csvData = [];
    csvData.push(['Report ID', 'Title', 'Status', 'Category', 'Location', 'Created At'].join(','));

    reportIds.forEach(id => {
      const reportCard = document.querySelector(`[data-report-id="${id}"]`);
      if (reportCard) {
        const title = reportCard.querySelector('.admin-report-head h3')?.textContent || '';
        const status = reportCard.querySelector('.admin-status-pill')?.textContent.replace('●', '').trim() || '';

        csvData.push([
          id,
          `"${title.replace(/"/g, '""')}"`,
          status,
          '', // category would need to be extracted
          '', // location would need to be extracted
          new Date().toISOString()
        ].join(','));
      }
    });

    const csvContent = csvData.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reports-export-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    toast(`Exported ${state.selectedReports.size} reports to CSV`);
  }

  // Filter functions
  function filterByStatus(status) {
    if (!elements.form) return;

    const statusSelect = elements.form.querySelector('select[name="status"]');
    if (statusSelect) {
      statusSelect.value = status;
      showLoading();
      elements.form.submit();
    }
  }

  function filterByPriority() {
    if (!elements.form) return;

    // Set high priority and date range (last 7 days)
    const fromInput = elements.form.querySelector('input[name="from"]');
    const toInput = elements.form.querySelector('input[name="to"]');
    const prioritySelect = elements.form.querySelector('select[name="priority"]');

    const today = new Date();
    const weekAgo = new Date(today);
    weekAgo.setDate(today.getDate() - 7);

    if (fromInput) fromInput.value = weekAgo.toISOString().split('T')[0];
    if (toInput) toInput.value = today.toISOString().split('T')[0];
    if (prioritySelect) prioritySelect.value = 'high';

    showLoading();
    elements.form.submit();
  }

  function filterByDate(period) {
    if (!elements.form) return;

    const fromInput = elements.form.querySelector('input[name="from"]');
    const toInput = elements.form.querySelector('input[name="to"]');
    const today = new Date().toISOString().split('T')[0];

    if (period === 'today') {
      if (fromInput) fromInput.value = today;
      if (toInput) toInput.value = today;
    }

    showLoading();
    elements.form.submit();
  }

  function generateReport() {
    const exportBtn = document.getElementById('exportBtn');
    if (exportBtn) exportBtn.click();
  }

  function quickStatusChange(element, reportId, currentStatus) {
    const statuses = ['pending', 'in_progress', 'resolved', 'rejected'];
    const labels = ['Pending', 'In Progress', 'Resolved', 'Rejected'];

    const choice = prompt(
      `Change status to:\n${labels.map((l, i) => `${i + 1}. ${l}`).join('\n')}\n\nEnter number (1-4):`
    );

    const index = parseInt(choice, 10) - 1;

    if (index >= 0 && index < statuses.length && statuses[index] !== currentStatus) {
      quickAction({ currentTarget: element }, reportId, statuses[index]);
    }
  }

  // Event handlers
  async function handleExport() {
    const exportBtn = document.getElementById('exportBtn');
    if (!exportBtn) return;

    const originalContent = exportBtn.innerHTML;
    exportBtn.disabled = true;
    exportBtn.innerHTML = '<div class="loading-spinner" style="width:1rem;height:1rem;"></div> Exporting...';

    try {
      const params = new URLSearchParams(window.location.search);
      params.set('export', 'csv');

      const response = await fetch(`${window.location.pathname}?${params}`);

      if (!response.ok) {
        throw new Error('Export failed');
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');

      a.href = url;
      a.download = `reports_export_${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);

      toast('Export completed successfully!');
    } catch (error) {
      console.error('Export failed:', error);
      toast('Export failed. Please try again.', 'error');
    } finally {
      exportBtn.disabled = false;
      exportBtn.innerHTML = originalContent;
    }
  }

  function handleSaveFilters() {
    const name = prompt('Enter a name for this filter set:');
    if (name) {
      const filterData = new URLSearchParams(window.location.search).toString();
      localStorage.setItem(`adminFilter_${name}`, filterData);
      toast(`Filter "${name}" saved!`);
    }
  }

  async function handleCopyLink() {
    const copyBtn = document.getElementById('copyLinkBtn');
    if (!copyBtn) return;

    try {
      await navigator.clipboard.writeText(window.location.href);
      toast('Link copied to clipboard!');

      const originalContent = copyBtn.innerHTML;
      copyBtn.innerHTML = '<svg class="h-4 w-4" viewBox="0 0 24 24" fill="currentColor"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>Copied!';
      setTimeout(() => {
        copyBtn.innerHTML = originalContent;
      }, 2000);
    } catch (error) {
      console.error('Copy failed:', error);
      toast('Failed to copy link', 'error');
    }
  }

  // Initialize when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  // Hide loading overlay on window load
  window.addEventListener('load', hideLoading);

  // Public API
  return {
    updateBulkSelection,
    toggleSelectAll,
    quickAction,
    assignToMe,
    bulkAction,
    clearBulkSelection,
    bulkExport,
    filterByStatus,
    filterByPriority,
    filterByDate,
    generateReport,
    quickStatusChange
  };
})();
</script>
@endpush
